server:
  port: 443
  ssl:
    key-store: classpath:pi-home.cn.jks
    key-store-type: JKS
    key-password: zan13d9446f
  context-path: /mini-weixin
debug: true
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  miniapp:
    appid: wxa19c6db8a8b95521
    secret: a6e0b91b7fb92ddef02c4f2d275df579
    token: yohu
    aesKey: t4Qddp9QSZZgH3NDIRjC93QacrFKr6mW7LErKTWrJBb
    msgDataFormat: JSON

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pi-home?useUnicode=true
    username: root
    password: 1234
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)